Move the 'complain_if_afids' check to common.am, so it applies to all builds

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -1997,7 +1997,7 @@ lib_LTLIBRARIES = $(am__append_8) $(am__append_37)
 noinst_LTLIBRARIES = $(am__append_7)
 dist_bin_SCRIPTS = $(am__append_45)
 AM_LDFLAGS = 
-BUILT_SOURCES = $(am__append_36) $(am__append_39)
+BUILT_SOURCES = complain_if_afids $(am__append_36) $(am__append_39)
 include_HEADERS = 
 EXTRA_DIST = $(am__append_5) $(am__append_9) $(am__append_11) \
 	$(am__append_41) $(am__append_47)
@@ -8867,6 +8867,22 @@ install-data-hook: $(INSTALL_DATA_HOOK)
 uninstall-hook: $(UNINSTALL_HOOK)
 clean-local: $(CLEAN_HOOK)
 installcheck-local: $(INSTALLCHECK_HOOK)
+
+# ========================================================================
+# An error we run into every once in a while is somebody trying to build
+# after having doing a setup_afids_env. The problem with this is that
+# the AFIDS distribution contains a program "sort" that interfers with the
+# unix sort.
+
+complain_if_afids:
+	@if test -n "${AFIDSTOP}"; then \
+          echo "${red}You have sourced setup_afids_env.sh or setup_afids_env.csh.";  \
+          echo "This will cause the build to *fail*, because MIPL has";  \
+          echo "a program called 'sort' that interferes with the unix";  \
+          echo "sort command. You need to restart the build *without*"; \
+          echo "sourcing setup_afids_env.sh or setup_afids_env.csh${default}"; \
+          exit 1; \
+        fi
 
 #=================================================================
 # Target to just install geocal
